name: Ping Hugging Face Space

on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes
  workflow_dispatch: # Allow manual triggering

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping Hugging Face Space
        run: curl -sSf https://nim23-whisper-api.hf.space || echo "Ping failed"
